### ISSUE TITLE
/etc/cron.d/freshrss incorrect

### ISSUE THREAD

**Issue by swinkl3** [linuxserver/docker-freshrss#2]
Hi, currently the freshrss cron file in /etc/cron.d does not run properly. When interrogating the cron syslog the following error is thrown:

Error: bad username; while reading /etc/cron.d/freshrss
ERROR (Syntax error, this crontab file will be ignored)

The cron file needs to be modified to include the user who is running the job. A line like below is now successfully running for me:
*/15 * * * * root php /config/www/freshrss/app/actualize_script.php > /tmp/FreshRSS.log 2>&1

**Comment by phendryx** [comment]
In addition to that, the permissions are wrong on the cron file. Both issues have been addressed in #6. Should be merged soon.
