### ISSUE TITLE
Container updates do not update freshrss

### ISSUE THREAD

**Issue by SuperSandro2000** [linuxserver/docker-freshrss#25]
Updates to the freshrss container do not update the freshrss version what makes them totally useless.

I suggest removing https://github.com/linuxserver/docker-freshrss/blob/master/root/etc/cont-init.d/40-install and putting the actual files in the container at build time and volume the ``/var/www/freshrss/data/`` directory.

**Comment by kt1024** [comment]
no idea what it means, tried many times with latest image.

>
```
[cont-init.d] 40-install: executing... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     13      0 --:--:-- --:--:-- --:--:--    13
tar: invalid tar magic
[cont-init.d] 40-install: exited 0.
[cont-init.d] done.

```

**Comment by SuperSandro2000** [comment]
@kt1024 that this container is a total waste of your time and can't update freshrss.

**Comment by CHBMB** [comment]
@superSandro2000 You are perfectly welcome to fork it and produce your own container or submit a PR.

**Comment by SuperSandro2000** [comment]
Or I just use this https://hub.docker.com/r/freshrss/freshrss image which perfectly works and is maintained by the creator of FreshRSS. If I need it for another arch it is easy to port and probably only requires a base image change and the QEMU RUNs.

So I won't put any work in this image except a warning should probably be added that it does not work as expected.

**Comment by CHBMB** [comment]
@supersandro2000 well do that then.

**Comment by SuperSandro2000** [comment]
This issue was open for 2.5 months and I talked to you guys about it in Discord, too.
No one saw this as a serious issue or admitted that updates are broken.
I don't have the time to write a new docker image if there is already an existing one that works very well and copying that is against the law.

What I can do is add a notice for you #26

**Comment by thelamer** [comment]
This was created before my time and yes it does not auto update. 
Please do not comment on our repos ever again. 
You are not helpful and are oddly aggressive about the fact that this image installs on first boot up. 

It is open source and people do this shit for free, think about your comments before participating again.

**Comment by SuperSandro2000** [comment]
Maybe do something about it other than just having it sit here! You are ignoring this issue since months!
