### ISSUE TITLE
enable php's opcache

### ISSUE THREAD

**Issue by Zayon** [linuxserver/docker-freshrss#28]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

For better performances and to reduce server load, it would be useful to use php opcache

**Comment by aptalca** [comment]
Shouldn't this be for the upstream app?

**Comment by Zayon** [comment]
Wow that was closed fast

Anyway why do you mean by:

> Shouldn't this be for the upstream app?

Opcache is a server configuration. It does not have anything to do with the code of the app.

Activating it would require to install the php extension php-opcache and to enable it, maybe tweek some `php.ini` optimisation and voilà.

**Comment by aptalca** [comment]
3 days with no reply is hardly fast. Feel free to reopen if you want to continue discussion. We get too many issues opened where the author never comes back.

We could add the opcache module package but without the php.ini, it won't do anything. We would need upstream's recommendation and guidance on the specific settings. Currently, they don't have any. They don't list opcache as a recommended module either.

Also, what kind of benefit are you looking to achieve? According to freshrss github, it is very lightweight: `It even works on Raspberry Pi 1 with response time under a second (tested with 150 feeds, 22k articles)`. Opcache is typically used on servers under high load with very frequent requests.
