### ISSUE TITLE
Android client cannot connect to API.

### ISSUE THREAD

**Issue by NoxInmortus** [linuxserver/docker-freshrss#29]
Hello,

I'm currently testing Freshrss since a few weeks, and I'm trying freshrss android app.

It seems that I cannot reach `https://myfreshrss-instance.xx/api/greader.php` or `https://myfreshrss-instance.xx/p/api/greader.php` as I read from some posts like this one :
`https://github.com/FreshRSS/FreshRSS/issues/957`

Api is enabled, and password for api has been setup.

Latest docker image on Debian 9.9 arm64.

Any hints ? I wonder if it doesnt come from the nginx configuration.

**Comment by homerr** [comment]
Are you using our LetsEncrypt container, and the FreshRSS conf we provide for it?

**Comment by NoxInmortus** [comment]
Hello,

No, I'm using haproxy as a reverse-proxy in front, redirecting everything with my host header to the container. Nothing fancy.

**Comment by NoxInmortus** [comment]
Hello, what about this issue ? Can you confirm that it works with your standard configuration ?

**Comment by j0nnymoe** [comment]
Here is the nginx reverse proxy config we supply with our letsencrypt container: https://github.com/linuxserver/reverse-proxy-confs/blob/master/freshrss.subdomain.conf.sample

Check that and do the same settings for your haproxy setup and see what happens.

**Comment by NoxInmortus** [comment]
Well it seems the issue has been resolved with one of the latest update without to edit anything. Cheers
