### ISSUE TITLE
Why there isn't a version without nginx?

### ISSUE THREAD

**Issue by lihsai0** [linuxserver/docker-freshrss#30]
Only question

## Context

I already have a container running nginx.

## Expected Behavior

There is a version only has php environment and Fresh RSS. No Nginx.

## Current Behavior

Request fresh-rss.example.com  
->  
nginx container(not fresh container)  
->  
nginx in fresh rss container  
->  
php

There also has two log location in tow nginx. I think it's redundancy.

**Comment by aptalca** [comment]
Currently there are no plans to make a php only freshrss image

**Comment by lihsai0** [comment]
If I disturb you, I apologize.

I was sadly to receive [no plans to make php only image] reply. So I make it by myself.

[docker-iobase-php](https://github.com/lihsai0/docker-iobase-php)  
[docker-freshrss](https://github.com/lihsai0/docker-freshrss)

They are based on Linux Server's work.

But because of my poor technology on Docker and PHP. They are ugly. Just can run.

If anyone can give me some suggestions, I will be very grateful to you.
