### ISSUE TITLE
TZ environment variable not used by PHP

### ISSUE THREAD

**Issue by iyerusad** [linuxserver/docker-freshrss#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Setting `TZ` environment variable sets timezone

## Current Behavior
PHP within container is not aware of `TZ` environment variable setting.

Apparently, PHP is not using the system parameters since PHP 5.4 http://php.net/manual/function.date-default-timezone-get.php

This is fixed upstream in https://github.com/FreshRSS/FreshRSS/pull/2218. Discussed in https://github.com/FreshRSS/FreshRSS/issues/2153.

## Steps to Reproduce
1. Within container run `php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'`

or 

1. `sudo docker run -it -e TZ=Europe/Paris --rm linuxserver/freshrss:latest php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'`

## Environment
**OS:** Synology     
**CPU architecture:** x86_64    
**How docker service was installed:** Synology package

## Command used to create docker container (run/create/compose/screenshot)
`sudo docker run -it -e TZ=Europe/Paris --rm linuxserver/freshrss:latest php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'`

## Docker logs
`php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'`
```
UTC
2020-02-19T02:06:44+00:00
```

**Comment by aptalca** [comment]
Baseimage handles that for php-fpm during fresh start: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/cont-init.d/20-config#L20

**Comment by iyerusad** [comment]
> Baseimage handles that for php-fpm **during fresh start**: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/cont-init.d/20-config#L20

Wouldn't that make it not an environment variable then (rather, a first boot parameter)?

**Comment by aptalca** [comment]
It's an environment variable for the container OS.

For php, it's a first boot parameter because it is set in a user configurable file and we don't modify those after creation to ensure we don't overwrite user settings

**Comment by iyerusad** [comment]
Sounds like there should be one of the following outcomes:

**A)** Remove `TZ` variable from this package (since it is unable to effectively define the timezone in the core runtime of this container, namely php).

**B)** Adopt upstream fix: Inject helper snippet to Docker file:
```
find /etc/php*/ -name php.ini -exec sed -r -i "\#^;?date.timezone#s#^.*#date.timezone = $TZ#" {} \;
```

**C)** Update `TZ` variable documentation to reflect its only used once (aka a build variable) and future updates are done via editing the php.ini file. Least desirable since whole point is to have environment variable be effective (in the context of the application that the container is hosting).

**Comment by aptalca** [comment]
Everything here is working as intended. If you want to change any php settings for any reason, edit the php-local.ini and/or www2.conf in the config for and restart the container

**Comment by kman3107** [comment]
For anyone that comes back here in the future and are as clueless as I am about these things. 

1. Find and open `php-local.ini` which in my cause (Unraid) was `nano /mnt/user/appdata/freshrss/php/php-local.ini`
2. Add your timezone, in my case `date.timezone = Europe/Berlin`
3. Save and close file
4. Restart container

This worked for me.

**Comment by jcabrerazuniga** [comment]
The problem with editing php.ini is that this will change every time an update is made to an app as the wiki container. Worst, the https://docs.linuxserver.io/images/docker-dokuwiki/ direct to use TZ as environment variable which does not work in my case:

```
root@pepewiki-577bc69f45-c6dkh:/etc/php84# date
Tue Jun 16 06:34:46 MDT 2026
root@pepewiki-577bc69f45-c6dkh:/etc/php84#     php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
UTC
2026-06-16T12:34:52+00:00
root@pepewiki-577bc69f45-c6dkh:/etc/php84# echo $TZ
America/Denver
```

I will try editing php-local.ini but if TZ is not going to work then better to update the documentation. Could the next be correct?

```
cat /config/php/php-local.ini
; Edit this file to override php.ini directives

upload_max_filesize = 100M
post_max_size = 100M
date.timezone = ${TZ}
```

**Comment by aptalca** [comment]
TZ value is written to php-local.ini the first time the container is run. If you create the container without setting TZ the first time, it won't have your local TZ in it. You have to edit it yourself.

The reason we don't modify php-local.ini after first run is because it's meant to be user customizable and we don't want to accidentally overwrite user edits. We create it for you the first time, then you manage it. I don't know why this is such a difficult concept for some.

> The problem with editing php.ini is that this will change every time an update is made to an app as the wiki container.

I don't know what you mean by this. `php-local.ini` is in the config folder under `php/`. It only needs to be set once, which is done on first start as long as you followed our instructions and set the TZ var correctly that first time.
