### ISSUE TITLE
Unable to start new freshrss instance

### ISSUE THREAD

**Issue by Arwalk** [linuxserver/docker-freshrss#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Starting a new freshrss instance should work after installation

## Current Behavior
The instances starts its install process, then fails on the keygen step.

`3069531024:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:`

The rest of the installation fails, with the repeating log here when nginx tries to start.

`nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

## Steps to Reproduce
1. Run a fresh new instance with the command
`docker create -t --name freshrss -p 32774:80 -e TZ=Europe/Paris -v /home/pi/docker/freshrss:/config --restart unless-stopped linuxserver/freshrss:arm32v7-latest`

## Environment
**OS:** Raspbian 
**CPU architecture:**  arm32, running on a Raspberry PI 4.
**How docker service was installed:**
Official docker repo

## Command used to create docker container (run/create/compose/screenshot)
`docker create -t --name freshrss -p 32774:80 -e TZ=Europe/Paris -v /home/pi/docker/freshrss:/config --restart unless-stopped linuxserver/freshrss:arm32v7-latest`

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
.........................................................................................................................................................+++++
............................................+++++
writing new private key to '/config/keys/cert.key'
-----
3069531024:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
[cont-init.d] 30-keygen: exited 1.
[cont-init.d] 40-install: executing...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
crond[329]: crond (busybox 1.32.1) started, log level 5
[services.d] done.
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routi
nes:BIO_new_file:no such file)
[16-May-2071 08:36:48] NOTICE: fpm is running, pid 326
[16-May-2071 08:35:28] NOTICE: ready to handle connections
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routi
nes:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routi
nes:BIO_new_file:no such file)
```

Latest line of logs repeats itself.

On a side note, i've had problems with the latest releases since 10/02/2021, as my existing freshrss instance was failing to update any feed. I sadly have not kept any logs nor informations about this problem, so i can't say if there's a link, or if it's only freshrss's problem.

**Comment by Roxedus** [comment]
> Your DockerHost is most likely running an outdated version of libseccomp

> To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Log tells you what to do

**Comment by Arwalk** [comment]
Indeed. That fixed it. Don't mind my retardation, closing.
