### ISSUE TITLE
BASE_URL env variable

### ISSUE THREAD

**Issue by pr3d1** [linuxserver/docker-freshrss#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Defining a BASE_URL env variable for the container.  
------------------------------

## Desired Behavior

I need to modify the base_url parameter inside the config.php file. I think it would be nice if the container could accept a BASE_URL env variable, like in [this](https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/example.env) page.

## Current Behavior
The BASE_URL env variable does not affect for the config.php file.

## Alternatives Considered
I defined a K8S configmap and used it for this purpose, but i think it would be nice, if we can use an env variable for this purpose.

**Comment by nemchik** [comment]
I'm not entirely sure how the app inside the container is reading the variable from the environment. I searched `BASE_URL` in the upstream repo and it mostly just looks like it reads from the config file, not the environment. If you have any more information about how this is expected to be handled I would be open to making adjustments here.

**Comment by drizuid** [comment]
No further info provided by OP, closing.
