### ISSUE TITLE
[FEAT] Changing the cronjob interval

### ISSUE THREAD

**Issue by broizter** [linuxserver/docker-freshrss#55]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Currently the feeds will update every 15 minutes because of the cronjob in the container. It would be nice if this could be configured via an environment variable for example.

```bash
cat /etc/crontabs/root

# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# freshrss cronjob
*/15    *       *       *       *       /usr/bin/php /app/www/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

### Reason for change

To reduce CPU load on the host machine and whatever load it puts on the feeds. I'm sure it can be argued that it's negligible but for me personally there's no reason for the feeds to update that often. Once per hour or even less often is more than fine.

![image](https://user-images.githubusercontent.com/39500356/232888733-fa74aa2d-ed7f-45ba-9d20-b3b84d0973b1.png)

**Comment by aptalca** [comment]
I'll be honest, the graph you posted had the opposite effect on me. I barely see any cpu utilization there and I don't think this justifies adding an env var for.

You can customize the container however: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by aptalca** [comment]
Oh wait, I had a senior moment. The actual crontab is in the config folder and is user customizable already.

**Comment by broizter** [comment]
> Oh wait, I had a senior moment. The actual crontab is in the config folder and is user customizable already.

Well, I'm the one with that had a senior moment opening this feature request without realising its already possible to achieve what I wanted. My apologies!

**Comment by denilsonsa** [comment]
> The actual crontab is in the config folder and is user customizable already.

For anyone aiming to customize the crontab, please note that #50 changed that behavior, and the crontab isn't in the config folder anymore.

In my case, not only it was a waste of CPU to run it every 15 minutes, but it was also noisy, as this specific machine has a spinning disk and I can hear the disk working for several minutes very often.

My solution/workaround:

```yaml
    volumes:
      - ./config:/config
      - ./crontabs:/etc/crontabs
```

And then I initialize that folder with https://github.com/linuxserver/docker-freshrss/blob/master/root/etc/crontabs/abc

I haven't spent enough time to check if it worked or not. I hope it did.
