### ISSUE TITLE
[FEAT] OIDC Support

### ISSUE THREAD

**Issue by CallMeTerdFerguson** [linuxserver/docker-freshrss#60]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

FreshRSS added support for OIDC recently using libapache2-mod-auth-openidc in their Debian image. It looks like the upstream changes to the FreshRSS code have been pulled by the LSIO build and my container reports it is on the right version (1.22) but OIDC doesn't appear to be functional, at least assuming I've got my configuration right per the FreshRSS documentation. Should it be working in the current image and if not, can you update the LSIO image to support it or will users who want OIDC need to move to the freshrss Debian image?

### Reason for change

OIDC support enables SSO support without having to proxy the endpoint and is a popular way to enable SSO on homelabs.

**Comment by aptalca** [comment]
I took a quick look and if I'm not mistaken, their oidc implementation only works when served by Apache. Unfortunately we only support Nginx.
