### ISSUE TITLE
[FEAT] Env variable to setup cron schedule

### ISSUE THREAD

**Issue by xRahul** [linuxserver/docker-freshrss#70]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can we have an env variable to setup cron schedule?

### Reason for change

I'm not sure how to set the frequency of updates. But during update everything becomes very slow, so it'd help if we can change it. It is there in main freshrss image also

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-11-02-cron/

**Comment by aptalca** [comment]
This is the current `abc` crontab used in the container: https://github.com/linuxserver/docker-freshrss/blob/master/root/etc/crontabs/abc#L2

The mod makes the `abc` crontab available for editing in the config folder, which should be mapped on your host. I don't recall off the top of my head whether the mod will copy that crontab in use to the config foler or just create a blank one for you to edit. But the original one is linked above and it's set to run every 15 minutes.
